In [2]:
import carla
import numpy as np
from scipy.spatial.transform import Rotation as Rot

In [18]:
pitch = 10
yaw = 2
roll = 5
carla_transform = carla.Transform(carla.Location(x = 0, y = 0, z = 0),
                                  carla.Rotation(pitch,yaw,roll))


In [19]:
carla_rmat = np.array(carla_transform.get_matrix())[0:3,0:3]
carla_rmat

array([[ 0.98420781, -0.01964148, -0.17592371],
       [ 0.03436929,  0.99611604,  0.08106547],
       [ 0.17364818, -0.08583164,  0.98106027]])

In [26]:
theta_x = pitch
theta_y = yaw
theta_z = roll
opencv_rmat = Rot.from_euler('xyz',np.array([theta_x,theta_y,theta_z]),degrees=True).as_matrix()
opencv_rmat


array([[ 0.99558784, -0.07979448,  0.04937295],
       [ 0.08710265,  0.98158845, -0.16999191],
       [-0.0348995 ,  0.1735424 ,  0.98420783]])

In [27]:
P_carla_to_opencv = np.array([[0, 1, 0],
                              [0, 0,-1],
                              [1, 0, 0]])

In [28]:
P_carla_to_opencv @ carla_rmat @ np.linalg.inv(P_carla_to_opencv)

array([[ 0.99611604, -0.08106547,  0.03436929],
       [ 0.08583164,  0.98106027, -0.17364818],
       [-0.01964148,  0.17592371,  0.98420781]])