In [21]:
import sympy
import numpy as np
import carla
from scipy.spatial.transform import Rotation as Rot
import math

In [4]:
P_carla_to_opencv = sympy.Matrix([[0, 1, 0, 0],
                                  [0, 0,-1, 0],
                                  [1, 0, 0, 0],
                                  [0, 0, 0, 1]])
P_carla_to_opencv

Matrix([
[0, 1,  0, 0],
[0, 0, -1, 0],
[1, 0,  0, 0],
[0, 0,  0, 1]])

In [9]:
r11_c,r12_c,r13_c = sympy.Symbol('r^{c}_{11}'),sympy.Symbol('r^{c}_{12}'),sympy.Symbol('r^{c}_{13}')
r21_c,r22_c,r23_c = sympy.Symbol('r^{c}_{21}'),sympy.Symbol('r^{c}_{22}'),sympy.Symbol('r^{c}_{23}')
r31_c,r32_c,r33_c = sympy.Symbol('r^{c}_{31}'),sympy.Symbol('r^{c}_{32}'),sympy.Symbol('r^{c}_{33}')
x_c,y_c,z_c = sympy.Symbol('x^{c}'),sympy.Symbol('y^{c}'),sympy.Symbol('z^{c}')

T_carla = sympy.Matrix([[r11_c,r12_c,r13_c,x_c],
                        [r21_c,r22_c,r23_c,y_c],
                        [r31_c,r32_c,r33_c,z_c],
                        [0,    0,    0,    1]])
T_carla

Matrix([
[r^{c}_{11}, r^{c}_{12}, r^{c}_{13}, x^{c}],
[r^{c}_{21}, r^{c}_{22}, r^{c}_{23}, y^{c}],
[r^{c}_{31}, r^{c}_{32}, r^{c}_{33}, z^{c}],
[         0,          0,          0,     1]])

In [11]:
P_carla_to_opencv @ T_carla @ P_carla_to_opencv.inv()

Matrix([
[ r^{c}_{22}, -r^{c}_{23},  r^{c}_{21},  y^{c}],
[-r^{c}_{32},  r^{c}_{33}, -r^{c}_{31}, -z^{c}],
[ r^{c}_{12}, -r^{c}_{13},  r^{c}_{11},  x^{c}],
[          0,           0,           0,      1]])

---

In [22]:
def degree_to_radian(theta):
    return math.pi * theta / 180.0

In [60]:
ryaw = 0.0
rpitch = 0.0
rroll = 1.0
tx = 1.0
ty = 2.0
tz = 3.0
r = carla.Transform(carla.Location(x = tx, y = ty, z = tz),
                    carla.Rotation(pitch = rpitch, yaw = ryaw, roll = rroll))
Tc = np.array(r.get_matrix())
print(Tc)

[[ 1.          0.         -0.          1.        ]
 [ 0.          0.99984771  0.01745241  2.        ]
 [ 0.         -0.01745241  0.99984771  3.        ]
 [ 0.          0.          0.          1.        ]]


In [61]:
P = np.array([[0, 1, 0,  0],
              [0, 0, -1, 0],
              [1, 0, 0,  0],
              [0, 0, 0,  1]])
To = P @ Tc @ np.linalg.inv(P)
To

array([[ 0.99984771, -0.01745241,  0.        ,  2.        ],
       [ 0.01745241,  0.99984771,  0.        , -3.        ],
       [ 0.        ,  0.        ,  1.        ,  1.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [62]:
Rot.from_matrix(Tc[0:3,0:3]).as_rotvec(degrees=True)

array([-0.99999995, -0.        ,  0.        ])

In [63]:
Rot.from_matrix(To[0:3,0:3]).as_rotvec(degrees=True)

array([0.        , 0.        , 0.99999995])